export const data = [{
    "idMeal": "53026",
    "strMeal": "Tamiya",
    "strDrinkAlternate": null,
    "strCategory": "Vegetarian",
    "strArea": "Egyptian",
    "strInstructions": "oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=mulqW-J3Yy4",
    "strIngredient1": "Broad Beans",
    "strIngredient2": "Spring Onions",
    "strIngredient3": "Garlic Clove",
    "strIngredient4": "Parsley",
    "strIngredient5": "Cumin",
    "strIngredient6": "Baking Powder",
    "strIngredient7": "Cayenne Pepper",
    "strIngredient8": "Flour",
    "strIngredient9": "Vegetable Oil",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "3 cups ",
    "strMeasure2": "6",
    "strMeasure3": "4",
    "strMeasure4": "1/4 cup",
    "strMeasure5": "2 tsp",
    "strMeasure6": "1 tsp ",
    "strMeasure7": "1/2 tsp",
    "strMeasure8": "Spinkling",
    "strMeasure9": "As required",
    "strMeasure10": " ",
    "strMeasure11": " ",
    "strMeasure12": " ",
    "strMeasure13": " ",
    "strMeasure14": " ",
    "strMeasure15": " ",
    "strMeasure16": " ",
    "strMeasure17": " ",
    "strMeasure18": " ",
    "strMeasure19": " ",
    "strMeasure20": " ",
    "strSource": "https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/",
    "strImageSource": null,
    "strCreativeCommonsConfirmed": null,
    "dateModified": null
  },
  {
    "idMeal": "52793",
    "strMeal": "Sticky Toffee Pudding Ultimate",
    "strDrinkAlternate": null,
    "strCategory": "Dessert",
    "strArea": "British",
    "strInstructions": "Stone and chop the dates quite small, put them in a bowl, then pour the boiling water over. Leave for about 30 mins until cool and well-soaked, then mash a bit with a fork. Stir in the vanilla extract. Butter and flour seven mini pudding tins (each about 200ml/7fl oz) and sit them on a baking sheet. Heat oven to 180C/fan 160C/gas 4.\r\nWhile the dates are soaking, make the puddings. Mix the flour and bicarbonate of soda together and beat the eggs in a separate bowl. Beat the butter and sugar together in a large bowl for a few mins until slightly creamy (the mixture will be grainy from the sugar). Add the eggs a little at a time, beating well between additions. Beat in the black treacle then, using a large metal spoon, gently fold in one-third of the flour, then half the milk, being careful not to overbeat. Repeat until all the flour and milk is used. Stir the soaked dates into the pudding batter. The mix may look a little curdled at this point and will be like a soft, thick batter. Spoon it evenly between the tins and bake for 20-25 mins, until risen and firm.\r\nMeanwhile, put the sugar and butter for the sauce in a medium saucepan with half the cream. Bring to the boil over a medium heat, stirring all the time, until the sugar has completely dissolved. Stir in the black treacle, turn up the heat slightly and let the mixture bubble away for 2-3 mins until it is a rich toffee colour, stirring occasionally to make sure it doesn’t burn. Take the pan off the heat and beat in the rest of the cream.\r\nRemove the puddings from the oven. Leave in the tins for a few mins, then loosen them well from the sides of the tins with a small palette knife before turning them out. You can serve them now with the sauce drizzled over, but they’ll be even stickier if left for a day or two coated in the sauce. To do this, pour about half the sauce into one or two ovenproof serving dishes. Sit the upturned puddings on the sauce, then pour the rest of the sauce over them. Cover with a loose tent of foil so that the sauce doesn’t smudge (no need to chill).\r\nWhen ready to serve, heat oven to 180C/fan 160C/gas 4. Warm the puddings through, still covered, for 15-20 mins or until the sauce is bubbling. Serve them on their own, or with cream or custard.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/xrptpq1483909204.jpg",
    "strTags": "Pudding,Desert,Cake,Dairy",
    "strYoutube": "https://www.youtube.com/watch?v=hKq6RbxJHBo",
    "strIngredient1": "Medjool dates",
    "strIngredient2": "water",
    "strIngredient3": "vanilla extract",
    "strIngredient4": "self-raising flour",
    "strIngredient5": "bicarbonate of soda",
    "strIngredient6": "eggs",
    "strIngredient7": "butter",
    "strIngredient8": "demerara sugar",
    "strIngredient9": "black treacle",
    "strIngredient10": "milk",
    "strIngredient11": "ice cream",
    "strIngredient12": "muscovado sugar",
    "strIngredient13": "butter",
    "strIngredient14": "double cream",
    "strIngredient15": "black treacle",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "225g",
    "strMeasure2": "175ml Boiling",
    "strMeasure3": "1 tsp",
    "strMeasure4": "175g",
    "strMeasure5": "1 tsp",
    "strMeasure6": "2",
    "strMeasure7": "85g",
    "strMeasure8": "140g",
    "strMeasure9": "2 tbsp",
    "strMeasure10": "100ml",
    "strMeasure11": "1 scoop",
    "strMeasure12": "175g",
    "strMeasure13": "50g",
    "strMeasure14": "225ml",
    "strMeasure15": "1 tbsp",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.youtube.com/watch?v=Wytv3bjqJII",
    "strImageSource": null,
    "strCreativeCommonsConfirmed": null,
    "dateModified": null
  },
  {
    "idMeal": "52832",
    "strMeal": "Coq au vin",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "French",
    "strInstructions": "Heat 1 tbsp of the oil in a large, heavy-based saucepan or flameproof dish. Tip in the bacon and fry until crisp. Remove and drain on kitchen paper. Add the shallots to the pan and fry, stirring or shaking the pan often, for 5-8 mins until well browned all over. Remove and set aside with the bacon.\r\nPat the chicken pieces dry with kitchen paper. Pour the remaining oil into the pan, then fry half the chicken pieces, turning regularly, for 5-8 mins until well browned. Remove, then repeat with the remaining chicken. Remove and set aside.\r\nScatter in the garlic and fry briefly, then, with the heat medium-high, pour in the brandy or Cognac, stirring the bottom of the pan to deglaze. The alcohol should sizzle and start to evaporate so there is not much left.\r\nReturn the chicken legs and thighs to the pan along with any juices, then pour in a little of the wine, stirring the bottom of the pan again. Stir in the rest of the wine, the stock and tomato purée, drop in the bouquet garni, season with pepper and a pinch of salt, then return the bacon and shallots to the pan. Cover, lower the heat to a gentle simmer, add the chicken breasts and cook for 50 mins-1hr.\r\nJust before ready to serve, heat the oil for the mushrooms in a large non-stick frying pan. Add the mushrooms and fry over a high heat for a few mins until golden. Remove and keep warm.\r\nLift the chicken, shallots and bacon from the pan and transfer to a warmed serving dish. Remove the bouquet garni. To make the thickener, mix the flour, olive oil and butter in a small bowl using the back of a teaspoon. Bring the wine mixture to a gentle boil, then gradually drop in small pieces of the thickener, whisking each piece in using a wire whisk. Simmer for 1-2 mins. Scatter the mushrooms over the chicken, then pour over the wine sauce. Garnish with chopped parsley.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=_ise46LADBs",
    "strIngredient1": "Olive Oil",
    "strIngredient2": "Bacon",
    "strIngredient3": "Shallots",
    "strIngredient4": "Chicken Legs",
    "strIngredient5": "Chicken Thighs",
    "strIngredient6": "Chicken Breasts",
    "strIngredient7": "Garlic",
    "strIngredient8": "Brandy",
    "strIngredient9": "Red Wine",
    "strIngredient10": "Chicken Stock",
    "strIngredient11": "tomato puree",
    "strIngredient12": "thyme",
    "strIngredient13": "Rosemary",
    "strIngredient14": "bay leaves",
    "strIngredient15": "parsley",
    "strIngredient16": "chestnut mushroom",
    "strIngredient17": "plain flour",
    "strIngredient18": "butter",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1½ tbsp",
    "strMeasure2": "3 rashers (100g) chopped dry-cured",
    "strMeasure3": "12 small",
    "strMeasure4": "2 (460g)",
    "strMeasure5": "4 (650g)",
    "strMeasure6": "2 (280g)",
    "strMeasure7": "3 finely chopped",
    "strMeasure8": "3 tbsp",
    "strMeasure9": "600ml",
    "strMeasure10": "150ml",
    "strMeasure11": "2 tsp",
    "strMeasure12": "3 sprigs",
    "strMeasure13": "2 sprigs",
    "strMeasure14": "2",
    "strMeasure15": "garnish",
    "strMeasure16": "250g",
    "strMeasure17": "2 tbsp",
    "strMeasure18": "1 tsp",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbcgoodfood.com/recipes/1913655/coq-au-vin",
    "strImageSource": null,
    "strCreativeCommonsConfirmed": null,
    "dateModified": null
  }
];